### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by shafqatvirk** [Garrafao/LSCDBenchmark#11]
I get the following runtime error:

Error executing job with overrides: ['task=wic', 'task/wic@task.model=contextual_embedder', 'task.model.ckpt=bert-base-german-cased', 'dataset=dwug_de_210', 'dataset.split=test', 'evaluation=wic', 'task/wic/normalization@task.model.normalization=l1', 'task/wic/scaler@task.model.scaler=minmax', 'task.model.layer_aggregation=average', 'task.model.subword_aggregation=average', 'task/wic/dist_fn@task.model.similarity_metric=dot']
Traceback (most recent call last):
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/main.py", line 12, in main
    run(*instantiate(config))
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/src/utils/runner.py", line 74, in run
    predictions.update(dict(zip(id_pairs, model.predict_all(use_pairs))))
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/src/wic/model.py", line 40, in predict_all
    predictions = self.scaler.fit_transform(predictions).flatten().tolist()
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/venv3.10/lib/python3.10/site-packages/sklearn/base.py", line 867, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/venv3.10/lib/python3.10/site-packages/sklearn/preprocessing/_data.py", line 420, in fit
    return self.partial_fit(X, y)
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/venv3.10/lib/python3.10/site-packages/sklearn/preprocessing/_data.py", line 457, in partial_fit
    X = self._validate_data(
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/venv3.10/lib/python3.10/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/venv3.10/lib/python3.10/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by MinMaxScaler.

**Comment by cbr9** [comment]
Hi Shafqat. This is because dwug_de_210 is a development dataset, so the test set is empty (you set dataset.split=test). The code should probably stop execution if you choose an empty split, and show some warning or error.

**Comment by shafqatvirk** [comment]
Thanks! And also, there should be some description of datasets some where.

**Comment by cbr9** [comment]
That will go in the docs, but it will take some time until they're ready

**Comment by shafqatvirk** [comment]
Here is the new one: 

Error executing job with overrides: ['task=wic', 'task/wic@task.model=contextual_embedder', 'task.model.ckpt=bert-base-german-cased', 'dataset=dwug_de_210', 'dataset.split=dev', 'evaluation=wic', 'task/wic/normalization@task.model.normalization=l1', 'task/wic/scaler@task.model.scaler=standard', 'task.model.layer_aggregation=average', 'task.model.subword_aggregation=average', 'task/wic/dist_fn@task.model.similarity_metric=cosine']
Traceback (most recent call last):
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/main.py", line 12, in main
    run(*instantiate(config))
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/src/utils/runner.py", line 74, in run
    predictions.update(dict(zip(id_pairs, model.predict_all(use_pairs))))
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/src/wic/model.py", line 43, in predict_all
    as_json = json.dumps(self.scaler.__dict__, cls=NumpyEncoder, indent=4)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xvirsh/shafqat/postDoc-Swe/project2022/LSCDBenchmark-latest/LSCDBenchmark/src/wic/model.py", line 26, in default
    return json.JSONEncoder.default(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable

**Comment by cbr9** [comment]
Fixed.
